### ISSUE TITLE
Player gets on fire after clearing the fire resistance effect by command

### ISSUE THREAD

**Issue by yermachello** [AndyRusso/dynamic-fire-overlay#2]
https://github.com/AndyRusso/dynamic-fire-overlay/assets/7390018/db525e29-4775-4d3f-aacd-3eda58e5cfcd

**Comment by AndyRusso** [comment]
Hello. It looks like everything is working as intended. What is your expected behavior?

**Comment by yermachello** [comment]
Sorry for crazy long replies!
I agree, the mod is working as intended — it hides the fire, and it doesn't make you not set on fire as I thought for some reason. Your mod made it feel like I'm not on fire at all and getting rid of the fire resistance effect made it feel like original fire is a bug, hahah

Here is some footage without the mod in case somebody is wondering:

https://github.com/AndyRusso/dynamic-fire-overlay/assets/7390018/2c8013e0-f9ab-47a0-a758-49512769e3c8

**Comment by AndyRusso** [comment]
Hello. No worries with the delay. Glad this is resolved!
